// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Cost for running a model deployment on a given instance type. Currently, only
/// USD currency code is supported.
public struct Cost: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The cost per million output tokens, calculated as:
  /// $/output token = GPU $/s / (1/output-to-input-cost-ratio * input tokens/s +
  /// output tokens/s)
  public var costPerMillionOutputTokens: Amount? = nil

  /// Optional. The cost per million input tokens. $/input token = ($/output
  /// token) / output-to-input-cost-ratio.
  public var costPerMillionInputTokens: Amount? = nil

  /// Optional. The pricing model used to calculate the cost. Can be one of:
  /// `3-years-cud`, `1-year-cud`, `on-demand`, `spot`. If not provided, `spot`
  /// will be used.
  public var pricingModel: Swift.String = Swift.String()

  /// Optional. The output-to-input cost ratio. This determines how the total GPU
  /// cost is split between input and output tokens. If not provided, `4.0` is
  /// used, assuming a 4:1 output:input cost ratio.
  public var outputInputCostRatio: Swift.Float? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cost`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cost().with { $0.costPerMillionOutputTokens = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let costPerMillionOutputTokens = CodingKeys(stringValue: "costPerMillionOutputTokens")
    static let costPerMillionInputTokens = CodingKeys(stringValue: "costPerMillionInputTokens")
    static let pricingModel = CodingKeys(stringValue: "pricingModel")
    static let outputInputCostRatio = CodingKeys(stringValue: "outputInputCostRatio")

    static let _knownKeys: Set<Swift.String> = [
      "costPerMillionOutputTokens",
      "costPerMillionInputTokens",
      "pricingModel",
      "outputInputCostRatio",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.costPerMillionOutputTokens = try container.decodeIfPresent(
      Amount.self, forKey: .costPerMillionOutputTokens)
    self.costPerMillionInputTokens = try container.decodeIfPresent(
      Amount.self, forKey: .costPerMillionInputTokens)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pricingModel) {
      self.pricingModel = value
    }
    self.outputInputCostRatio = try container.decodeIfPresent(
      Swift.Float.self, forKey: .outputInputCostRatio)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(
      self.costPerMillionOutputTokens, forKey: .costPerMillionOutputTokens)
    try container.encodeIfPresent(
      self.costPerMillionInputTokens, forKey: .costPerMillionInputTokens)
    try container.encode(self.pricingModel, forKey: .pricingModel)
    try container.encodeIfPresent(self.outputInputCostRatio, forKey: .outputInputCostRatio)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.Cost"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
