// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [GkeInferenceQuickstart.FetchModels][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]: <doc:GkeInferenceQuickstartClient/fetchModels(request:options:)>
public struct FetchModelsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The target number of results to return in a single response.
  /// If not specified, a default value will be chosen by the service.
  /// Note that the response may include a partial list and a caller should
  /// only rely on the response's
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchModelsResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkerecommender.v1.FetchModelsResponse.next_page_token]: <doc:FetchModelsResponse/nextPageToken>
  public var pageSize: Swift.Int32? = nil

  /// Optional. The value of
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchModelsResponse.next_page_token]
  /// received from a previous `FetchModelsRequest` call.
  /// Provide this to retrieve the subsequent page in a multi-page list of
  /// results. When paginating, all other parameters provided to
  /// `FetchModelsRequest` must match the call that provided the page token.
  ///
  /// [google.cloud.gkerecommender.v1.FetchModelsResponse.next_page_token]: <doc:FetchModelsResponse/nextPageToken>
  public var pageToken: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FetchModelsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchModelsRequest().with { $0.pageSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.pageSize = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.pageSize, forKey: .pageSize)
    try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchModelsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
