// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
public struct FetchProfilesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. List of profiles that match the given model server info and
  /// performance requirements (if provided).
  public var profile: [Profile] = []

  /// Output only. The combined range of performance values observed across all
  /// profiles in this response.
  public var performanceRange: PerformanceRange? = nil

  /// Output only. Additional comments related to the response.
  public var comments: Swift.String = Swift.String()

  /// Output only. A token which may be sent as
  /// [page_token][FetchProfilesResponse.page_token] in a subsequent
  /// `FetchProfilesResponse` call to retrieve the next page of results. If this
  /// field is omitted or empty, then there are no more results to return.
  public var nextPageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FetchProfilesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchProfilesResponse().with { $0.profile = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let profile = CodingKeys(stringValue: "profile")
    static let performanceRange = CodingKeys(stringValue: "performanceRange")
    static let comments = CodingKeys(stringValue: "comments")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

    static let _knownKeys: Set<Swift.String> = [
      "profile",
      "performanceRange",
      "comments",
      "nextPageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Profile].self, forKey: .profile) {
      self.profile = value
    }
    self.performanceRange = try container.decodeIfPresent(
      PerformanceRange.self, forKey: .performanceRange)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comments) {
      self.comments = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.profile, forKey: .profile)
    try container.encodeIfPresent(self.performanceRange, forKey: .performanceRange)
    try container.encode(self.comments, forKey: .comments)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchProfilesResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension FetchProfilesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [Profile] {
    return self.profile
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
