// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
public struct FetchProfilesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The model to filter profiles by. Open-source models follow the
  /// Huggingface Hub `owner/model_name` format. If not provided, all models are
  /// returned. Use
  /// [GkeInferenceQuickstart.FetchModels][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]
  /// to find available models.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModels]: <doc:GkeInferenceQuickstartClient/fetchModels(request:options:)>
  public var model: Swift.String = Swift.String()

  /// Optional. The model server to filter profiles by. If not provided, all
  /// model servers are returned. Use
  /// [GkeInferenceQuickstart.FetchModelServers][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]
  /// to find available model servers for a given model.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServers]: <doc:GkeInferenceQuickstartClient/fetchModelServers(request:options:)>
  public var modelServer: Swift.String = Swift.String()

  /// Optional. The model server version to filter profiles by. If not provided,
  /// all model server versions are returned. Use
  /// [GkeInferenceQuickstart.FetchModelServerVersions][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions]
  /// to find available versions for a given model and server.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchModelServerVersions]: <doc:GkeInferenceQuickstartClient/fetchModelServerVersions(request:options:)>
  public var modelServerVersion: Swift.String = Swift.String()

  /// Optional. The performance requirements to filter profiles. Profiles that do
  /// not meet these requirements are filtered out. If not provided, all profiles
  /// are returned.
  public var performanceRequirements: PerformanceRequirements? = nil

  /// Optional. The target number of results to return in a single response. If
  /// not specified, a default value will be chosen by the service. Note that the
  /// response may include a partial list and a caller should only rely on the
  /// response's
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]: <doc:FetchProfilesResponse/nextPageToken>
  public var pageSize: Swift.Int32? = nil

  /// Optional. The value of
  /// [next_page_token][google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]
  /// received from a previous `FetchProfilesRequest` call.
  /// Provide this to retrieve the subsequent page in a multi-page list of
  /// results. When paginating, all other parameters provided to
  /// `FetchProfilesRequest` must match the call that provided the page
  /// token.
  ///
  /// [google.cloud.gkerecommender.v1.FetchProfilesResponse.next_page_token]: <doc:FetchProfilesResponse/nextPageToken>
  public var pageToken: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FetchProfilesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchProfilesRequest().with { $0.model = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let model = CodingKeys(stringValue: "model")
    static let modelServer = CodingKeys(stringValue: "modelServer")
    static let modelServerVersion = CodingKeys(stringValue: "modelServerVersion")
    static let performanceRequirements = CodingKeys(stringValue: "performanceRequirements")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "model",
      "modelServer",
      "modelServerVersion",
      "performanceRequirements",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modelServer) {
      self.modelServer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modelServerVersion) {
      self.modelServerVersion = value
    }
    self.performanceRequirements = try container.decodeIfPresent(
      PerformanceRequirements.self, forKey: .performanceRequirements)
    self.pageSize = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.model, forKey: .model)
    try container.encode(self.modelServer, forKey: .modelServer)
    try container.encode(self.modelServerVersion, forKey: .modelServerVersion)
    try container.encodeIfPresent(self.performanceRequirements, forKey: .performanceRequirements)
    try container.encodeIfPresent(self.pageSize, forKey: .pageSize)
    try container.encodeIfPresent(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.FetchProfilesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
