// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [GkeInferenceQuickstart.GenerateOptimizedManifest][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest]: <doc:GkeInferenceQuickstartClient/generateOptimizedManifest(request:options:)>
public struct GenerateOptimizedManifestRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The model server configuration to generate the manifest for. Use
  /// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]
  /// to find valid configurations.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
  public var modelServerInfo: ModelServerInfo? = nil

  /// Required. The accelerator type. Use
  /// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]
  /// to find valid accelerators for a given `model_server_info`.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
  public var acceleratorType: Swift.String = Swift.String()

  /// Optional. The kubernetes namespace to deploy the manifests in.
  public var kubernetesNamespace: Swift.String = Swift.String()

  /// Optional. The performance requirements to use for generating Horizontal Pod
  /// Autoscaler (HPA) resources. If provided, the manifest includes HPA
  /// resources to adjust the model server replica count to maintain the
  /// specified targets (e.g., NTPOT, TTFT) at a P50 latency. Cost targets are
  /// not currently supported for HPA generation. If the specified targets are
  /// not achievable, the HPA manifest will not be generated.
  public var performanceRequirements: PerformanceRequirements? = nil

  /// Optional. The storage configuration for the model. If not provided, the
  /// model is loaded from Huggingface.
  public var storageConfig: StorageConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GenerateOptimizedManifestRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateOptimizedManifestRequest().with { $0.modelServerInfo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let modelServerInfo = CodingKeys(stringValue: "modelServerInfo")
    static let acceleratorType = CodingKeys(stringValue: "acceleratorType")
    static let kubernetesNamespace = CodingKeys(stringValue: "kubernetesNamespace")
    static let performanceRequirements = CodingKeys(stringValue: "performanceRequirements")
    static let storageConfig = CodingKeys(stringValue: "storageConfig")

    static let _knownKeys: Set<Swift.String> = [
      "modelServerInfo",
      "acceleratorType",
      "kubernetesNamespace",
      "performanceRequirements",
      "storageConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.modelServerInfo = try container.decodeIfPresent(
      ModelServerInfo.self, forKey: .modelServerInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .acceleratorType) {
      self.acceleratorType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kubernetesNamespace) {
      self.kubernetesNamespace = value
    }
    self.performanceRequirements = try container.decodeIfPresent(
      PerformanceRequirements.self, forKey: .performanceRequirements)
    self.storageConfig = try container.decodeIfPresent(StorageConfig.self, forKey: .storageConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.modelServerInfo, forKey: .modelServerInfo)
    try container.encode(self.acceleratorType, forKey: .acceleratorType)
    try container.encode(self.kubernetesNamespace, forKey: .kubernetesNamespace)
    try container.encodeIfPresent(self.performanceRequirements, forKey: .performanceRequirements)
    try container.encodeIfPresent(self.storageConfig, forKey: .storageConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.GenerateOptimizedManifestRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
