// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [GkeInferenceQuickstart.GenerateOptimizedManifest][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest].
///
/// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.GenerateOptimizedManifest]: <doc:GkeInferenceQuickstartClient/generateOptimizedManifest(request:options:)>
public struct GenerateOptimizedManifestResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. A list of generated Kubernetes manifests.
  public var kubernetesManifests: [KubernetesManifest] = []

  /// Output only. Comments related to deploying the generated manifests.
  public var comments: [Swift.String] = []

  /// Output only. Additional information about the versioned dependencies used
  /// to generate the manifests. See [Run best practice inference with GKE
  /// Inference Quickstart
  /// recipes](https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/inference-quickstart)
  /// for details.
  public var manifestVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GenerateOptimizedManifestResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateOptimizedManifestResponse().with { $0.kubernetesManifests = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kubernetesManifests = CodingKeys(stringValue: "kubernetesManifests")
    static let comments = CodingKeys(stringValue: "comments")
    static let manifestVersion = CodingKeys(stringValue: "manifestVersion")

    static let _knownKeys: Set<Swift.String> = [
      "kubernetesManifests",
      "comments",
      "manifestVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [KubernetesManifest].self, forKey: .kubernetesManifests)
    {
      self.kubernetesManifests = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .comments) {
      self.comments = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .manifestVersion) {
      self.manifestVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kubernetesManifests, forKey: .kubernetesManifests)
    try container.encode(self.comments, forKey: .comments)
    try container.encode(self.manifestVersion, forKey: .manifestVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.GenerateOptimizedManifestResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
