// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class GkeInferenceQuickstartRetry: GkeInferenceQuickstartStub {
    let inner: any GkeInferenceQuickstartStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any GkeInferenceQuickstartStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func fetchModels(
      request: FetchModelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchModelsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelsResponse
          in
          return try await self.inner.fetchModels(request: r, options: o)
        })
    }

    public func fetchModelServers(
      request: FetchModelServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchModelServersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelServersResponse
          in
          return try await self.inner.fetchModelServers(request: r, options: o)
        })
    }

    public func fetchModelServerVersions(
      request: FetchModelServerVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchModelServerVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse
          in
          return try await self.inner.fetchModelServerVersions(request: r, options: o)
        })
    }

    public func fetchProfiles(
      request: FetchProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FetchProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchProfilesResponse
          in
          return try await self.inner.fetchProfiles(request: r, options: o)
        })
    }

    public func generateOptimizedManifest(
      request: GenerateOptimizedManifestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GenerateOptimizedManifestRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse
          in
          return try await self.inner.generateOptimizedManifest(request: r, options: o)
        })
    }

    public func fetchBenchmarkingData(
      request: FetchBenchmarkingDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FetchBenchmarkingDataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse
          in
          return try await self.inner.fetchBenchmarkingData(request: r, options: o)
        })
    }
  }
}
