// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// GKE Inference Quickstart (GIQ) service provides profiles with performance
/// metrics for popular models and model servers across multiple accelerators.
/// These profiles help generate optimized best practices for running inference
/// on GKE.
///
/// @Snippet(path: "GkeInferenceQuickstartQuickstart")
public final class GkeInferenceQuickstartClient: Clients.GkeInferenceQuickstartProtocol, Sendable {
  let inner: any Clients.GkeInferenceQuickstartStub

  /// Creates a new `GkeInferenceQuickstartClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.GkeInferenceQuickstartStub = try Clients.GkeInferenceQuickstartTransport(
      options)
    inner = Clients.GkeInferenceQuickstartRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.GkeInferenceQuickstartLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Fetches available models. Open-source models follow the Huggingface Hub
  /// `owner/model_name` format.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchModels")
  public func fetchModels(
    request: FetchModelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse {
    try await self.inner.fetchModels(request: request, options: options)
  }

  /// Fetches available model servers. Open-source model servers use simplified,
  /// lowercase names (e.g., `vllm`).
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchModelServers")
  public func fetchModelServers(
    request: FetchModelServersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse {
    try await self.inner.fetchModelServers(request: request, options: options)
  }

  /// Fetches available model server versions. Open-source servers use their own
  /// versioning schemas (e.g., `vllm` uses semver like `v1.0.0`).
  ///
  /// Some model servers have different versioning schemas depending on the
  /// accelerator. For example, `vllm` uses semver on GPUs, but returns nightly
  /// build tags on TPUs. All available versions will be returned when different
  /// schemas are present.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchModelServerVersions")
  public func fetchModelServerVersions(
    request: FetchModelServerVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse {
    try await self.inner.fetchModelServerVersions(request: request, options: options)
  }

  /// Fetches available profiles. A profile contains performance metrics and
  /// cost information for a specific model server setup. Profiles can be
  /// filtered by parameters. If no filters are provided, all profiles are
  /// returned.
  ///
  /// Profiles display a single value per performance metric based on the
  /// provided performance requirements. If no requirements are given, the
  /// metrics represent the inflection point. See [Run best practice inference
  /// with GKE Inference Quickstart
  /// recipes](https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/inference-quickstart#how)
  /// for details.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchProfiles")
  public func fetchProfiles(
    request: FetchProfilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse {
    try await self.inner.fetchProfiles(request: request, options: options)
  }

  /// Generates an optimized deployment manifest for a given model and model
  /// server, based on the specified accelerator, performance targets, and
  /// configurations. See [Run best practice inference with GKE Inference
  /// Quickstart
  /// recipes](https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/inference-quickstart)
  /// for deployment details.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_GenerateOptimizedManifest")
  public func generateOptimizedManifest(
    request: GenerateOptimizedManifestRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse {
    try await self.inner.generateOptimizedManifest(request: request, options: options)
  }

  /// Fetches all of the benchmarking data available for a profile. Benchmarking
  /// data returns all of the performance metrics available for a given model
  /// server setup on a given instance type.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchBenchmarkingData")
  public func fetchBenchmarkingData(
    request: FetchBenchmarkingDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse {
    try await self.inner.fetchBenchmarkingData(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `GkeInferenceQuickstartClient`.
  ///
  /// To mock `GkeInferenceQuickstartClient` change your functions to receive
  /// `some GkeInferenceQuickstartProtocol` or `any GkeInferenceQuickstartProtocol`
  /// and pass a mock implementation in your tests.
  public protocol GkeInferenceQuickstartProtocol: Sendable {
    /// See `GkeInferenceQuickstartClient.fetchModels`.
    func fetchModels(
      request: FetchModelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse

    /// See `GkeInferenceQuickstartClient.fetchModelServers`.
    func fetchModelServers(
      request: FetchModelServersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse

    /// See `GkeInferenceQuickstartClient.fetchModelServerVersions`.
    func fetchModelServerVersions(
      request: FetchModelServerVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse

    /// See `GkeInferenceQuickstartClient.fetchProfiles`.
    func fetchProfiles(
      request: FetchProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse

    /// See `GkeInferenceQuickstartClient.generateOptimizedManifest`.
    func generateOptimizedManifest(
      request: GenerateOptimizedManifestRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse

    /// See `GkeInferenceQuickstartClient.fetchBenchmarkingData`.
    func fetchBenchmarkingData(
      request: FetchBenchmarkingDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse
  }
}

// Default implementations
extension Clients.GkeInferenceQuickstartProtocol {
  public func fetchModels(request: FetchModelsRequest) async throws
    -> GoogleCloudGKERecommenderV1.FetchModelsResponse
  {
    try await self.fetchModels(request: request, options: .init())
  }

  public func fetchModels(
    request: FetchModelsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchModelServers(request: FetchModelServersRequest) async throws
    -> GoogleCloudGKERecommenderV1.FetchModelServersResponse
  {
    try await self.fetchModelServers(request: request, options: .init())
  }

  public func fetchModelServers(
    request: FetchModelServersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchModelServerVersions(request: FetchModelServerVersionsRequest) async throws
    -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse
  {
    try await self.fetchModelServerVersions(request: request, options: .init())
  }

  public func fetchModelServerVersions(
    request: FetchModelServerVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchModelServerVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchProfiles(request: FetchProfilesRequest) async throws
    -> GoogleCloudGKERecommenderV1.FetchProfilesResponse
  {
    try await self.fetchProfiles(request: request, options: .init())
  }

  public func fetchProfiles(
    request: FetchProfilesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchProfiles(
    byItem: FetchProfilesRequest
  ) -> any AsyncSequence<Profile, Swift.Error> {
    self.fetchProfiles(byItem: byItem, options: .init())
  }

  /// Fetches available profiles. A profile contains performance metrics and
  /// cost information for a specific model server setup. Profiles can be
  /// filtered by parameters. If no filters are provided, all profiles are
  /// returned.
  ///
  /// Profiles display a single value per performance metric based on the
  /// provided performance requirements. If no requirements are given, the
  /// metrics represent the inflection point. See [Run best practice inference
  /// with GKE Inference Quickstart
  /// recipes](https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/inference-quickstart#how)
  /// for details.
  ///
  /// @Snippet(path: "GkeInferenceQuickstart_FetchProfiles")
  public func fetchProfiles(
    byItem: FetchProfilesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Profile, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKERecommenderV1.FetchProfilesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.fetchProfiles(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func generateOptimizedManifest(request: GenerateOptimizedManifestRequest) async throws
    -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse
  {
    try await self.generateOptimizedManifest(request: request, options: .init())
  }

  public func generateOptimizedManifest(
    request: GenerateOptimizedManifestRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.GenerateOptimizedManifestResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchBenchmarkingData(request: FetchBenchmarkingDataRequest) async throws
    -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse
  {
    try await self.fetchBenchmarkingData(request: request, options: .init())
  }

  public func fetchBenchmarkingData(
    request: FetchBenchmarkingDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudGKERecommenderV1.FetchBenchmarkingDataResponse {
    throw GoogleGax.RequestError.unimplemented
  }
}
