// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Performance statistics for a model deployment.
public struct PerformanceStats: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The number of queries per second.
  /// Note: This metric can vary widely based on context length and may not be a
  /// reliable measure of LLM throughput.
  public var queriesPerSecond: Swift.Float = Swift.Float()

  /// Output only. The number of output tokens per second. This is the throughput
  /// measured as total_output_tokens_generated_by_server /
  /// elapsed_time_in_seconds.
  public var outputTokensPerSecond: Swift.Int32 = Swift.Int32()

  /// Output only. The Normalized Time Per Output Token (NTPOT) in milliseconds.
  /// This is the request latency normalized by the number of output tokens,
  /// measured as request_latency / total_output_tokens.
  public var ntpotMilliseconds: Swift.Int32 = Swift.Int32()

  /// Output only. The Time To First Token (TTFT) in milliseconds. This is the
  /// time it takes to generate the first token for a request.
  public var ttftMilliseconds: Swift.Int32 = Swift.Int32()

  /// Output only. The cost of running the model deployment.
  public var cost: [Cost] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PerformanceStats`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PerformanceStats().with { $0.queriesPerSecond = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let queriesPerSecond = CodingKeys(stringValue: "queriesPerSecond")
    static let outputTokensPerSecond = CodingKeys(stringValue: "outputTokensPerSecond")
    static let ntpotMilliseconds = CodingKeys(stringValue: "ntpotMilliseconds")
    static let ttftMilliseconds = CodingKeys(stringValue: "ttftMilliseconds")
    static let cost = CodingKeys(stringValue: "cost")

    static let _knownKeys: Set<Swift.String> = [
      "queriesPerSecond",
      "outputTokensPerSecond",
      "ntpotMilliseconds",
      "ttftMilliseconds",
      "cost",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .queriesPerSecond) {
      self.queriesPerSecond = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .outputTokensPerSecond) {
      self.outputTokensPerSecond = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ntpotMilliseconds) {
      self.ntpotMilliseconds = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ttftMilliseconds) {
      self.ttftMilliseconds = value
    }
    if let value = try container.decodeIfPresent([Cost].self, forKey: .cost) {
      self.cost = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.queriesPerSecond, forKey: .queriesPerSecond)
    try container.encode(self.outputTokensPerSecond, forKey: .outputTokensPerSecond)
    try container.encode(self.ntpotMilliseconds, forKey: .ntpotMilliseconds)
    try container.encode(self.ttftMilliseconds, forKey: .ttftMilliseconds)
    try container.encode(self.cost, forKey: .cost)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.PerformanceStats"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
