// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A profile containing information about a model deployment.
public struct Profile: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The model server configuration. Use
  /// [GkeInferenceQuickstart.FetchProfiles][google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]
  /// to find valid configurations.
  ///
  /// [google.cloud.gkerecommender.v1.GkeInferenceQuickstart.FetchProfiles]: <doc:GkeInferenceQuickstartClient/fetchProfiles(request:options:)>
  public var modelServerInfo: ModelServerInfo? = nil

  /// Output only. The accelerator type. Expected format: `nvidia-h100-80gb`.
  public var acceleratorType: Swift.String = Swift.String()

  /// Output only. The TPU topology (if applicable).
  public var tpuTopology: Swift.String = Swift.String()

  /// Output only. The instance type. Expected format: `a2-highgpu-1g`.
  public var instanceType: Swift.String = Swift.String()

  /// Output only. The resources used by the model deployment.
  public var resourcesUsed: ResourcesUsed? = nil

  /// Output only. The performance statistics for this profile.
  public var performanceStats: [PerformanceStats] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Profile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Profile().with { $0.modelServerInfo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let modelServerInfo = CodingKeys(stringValue: "modelServerInfo")
    static let acceleratorType = CodingKeys(stringValue: "acceleratorType")
    static let tpuTopology = CodingKeys(stringValue: "tpuTopology")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let resourcesUsed = CodingKeys(stringValue: "resourcesUsed")
    static let performanceStats = CodingKeys(stringValue: "performanceStats")

    static let _knownKeys: Set<Swift.String> = [
      "modelServerInfo",
      "acceleratorType",
      "tpuTopology",
      "instanceType",
      "resourcesUsed",
      "performanceStats",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.modelServerInfo = try container.decodeIfPresent(
      ModelServerInfo.self, forKey: .modelServerInfo)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .acceleratorType) {
      self.acceleratorType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tpuTopology) {
      self.tpuTopology = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceType) {
      self.instanceType = value
    }
    self.resourcesUsed = try container.decodeIfPresent(ResourcesUsed.self, forKey: .resourcesUsed)
    if let value = try container.decodeIfPresent([PerformanceStats].self, forKey: .performanceStats)
    {
      self.performanceStats = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.modelServerInfo, forKey: .modelServerInfo)
    try container.encode(self.acceleratorType, forKey: .acceleratorType)
    try container.encode(self.tpuTopology, forKey: .tpuTopology)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encodeIfPresent(self.resourcesUsed, forKey: .resourcesUsed)
    try container.encode(self.performanceStats, forKey: .performanceStats)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.Profile"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
