// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Storage configuration for a model deployment.
public struct StorageConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The Google Cloud Storage bucket URI to load the model from. This
  /// URI must point to the directory containing the model's config file
  /// (`config.json`) and model weights. A tuned GCSFuse setup can improve
  /// LLM Pod startup time by more than 7x. Expected format:
  /// `gs://<bucket-name>/<path-to-model>`.
  public var modelBucketUri: Swift.String = Swift.String()

  /// Optional. The URI for the GCS bucket containing the XLA compilation cache.
  /// If using TPUs, the XLA cache will be written to the same path as
  /// `model_bucket_uri`. This can speed up vLLM model preparation for repeated
  /// deployments.
  public var xlaCacheBucketUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StorageConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageConfig().with { $0.modelBucketUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let modelBucketUri = CodingKeys(stringValue: "modelBucketUri")
    static let xlaCacheBucketUri = CodingKeys(stringValue: "xlaCacheBucketUri")

    static let _knownKeys: Set<Swift.String> = [
      "modelBucketUri",
      "xlaCacheBucketUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .modelBucketUri) {
      self.modelBucketUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .xlaCacheBucketUri) {
      self.xlaCacheBucketUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.modelBucketUri, forKey: .modelBucketUri)
    try container.encode(self.xlaCacheBucketUri, forKey: .xlaCacheBucketUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkerecommender.v1.StorageConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
